# Generated by Django 4.0.5 on 2022-07-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Сatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Наименование товара')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('weight', models.BooleanField(default=False, verbose_name='Вес')),
                ('price', models.BooleanField(default=False, verbose_name='Вес')),
            ],
            options={
                'verbose_name': 'Каталог продукции',
                'verbose_name_plural': 'Каталог продукции',
            },
        ),
    ]
