# Generated by Django 4.0.5 on 2022-07-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='сatalog',
            options={},
        ),
        migrations.AlterField(
            model_name='сatalog',
            name='price',
            field=models.BooleanField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='сatalog',
            name='weight',
            field=models.BooleanField(verbose_name='Вес'),
        ),
    ]
