# Generated by Django 4.0.5 on 2022-07-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_сatalog_options_alter_сatalog_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='Наименование')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Описание продукта')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('published', models.DateField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Сatalog',
        ),
    ]
