# Generated by Django 4.0.5 on 2022-08-22 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_product_categorys'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe_retailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_adress', models.CharField(max_length=75, verbose_name='Название/адрес')),
                ('time_create', models.DateField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Кафе/Магазин',
                'verbose_name_plural': 'Кафе/Магазины',
                'ordering': ['time_create', 'name_adress'],
            },
        ),
        migrations.CreateModel(
            name='Product_v',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Наименование')),
                ('time_create', models.DateField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Наименование',
                'verbose_name_plural': 'Наименования',
                'ordering': ['time_create', 'name'],
            },
        ),
        migrations.CreateModel(
            name='quantity_V',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField(auto_now_add=True, db_index=True, verbose_name='дата/время парсинга')),
                ('сafe_retailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.cafe_retailer')),
            ],
            options={
                'verbose_name': 'Количество в моменте',
                'verbose_name_plural': 'Количество в моменте',
                'ordering': ['date_time', 'сafe_retailer'],
            },
        ),
    ]
