# Generated by Django 4.0.5 on 2022-08-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_quantity_v_quantity_alter_cafe_retailer_name_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe_retailer',
            name='name_adress',
            field=models.TextField(blank=True, null=True, verbose_name='Название/адрес'),
        ),
    ]
