# Generated by Django 4.0.5 on 2022-07-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='Наименование')),
                ('time_create', models.DateField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('time_update', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['time_create', 'title'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='time_create',
            field=models.DateField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
    ]
