# Generated by Django 4.0.5 on 2022-08-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_cafe_retailer_product_v_quantity_v'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantity_v',
            name='quantity',
            field=models.FloatField(blank=True, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='cafe_retailer',
            name='name_adress',
            field=models.CharField(max_length=275, verbose_name='Название/адрес'),
        ),
    ]
