# Generated by Django 4.0.5 on 2023-08-08 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_product_v_options_alter_product_v_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_v',
        ),
        migrations.RemoveField(
            model_name='quantity_v',
            name='сafe_retailer',
        ),
        migrations.DeleteModel(
            name='Cafe_retailer',
        ),
        migrations.DeleteModel(
            name='quantity_V',
        ),
    ]
