# Generated by Django 4.0.5 on 2023-08-08 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_delete_product_v_remove_quantity_v_сafe_retailer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Старая цена')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='main.product')),
            ],
            options={
                'verbose_name': 'История цены',
                'verbose_name_plural': 'Истории цен',
                'ordering': ['-date'],
            },
        ),
    ]
