# Generated by Django 4.0.5 on 2023-08-08 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_product_image_promotion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorys',
            new_name='Category',
        ),
    ]
